server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeremywib7/microservices/tree/master/git-localconfig-repo
  application:
    name: spring-cloud-config-server
